# This is a basic workflow that is manually triggered

name: Manual_release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.0
    - name: npm install
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload
      uses: actions/upload-artifact@v3.0.0
      with:
        path: dist/*